<a href="https://colab.research.google.com/github/fox2056/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [2]:
A = np.array([3,1,4,2])
B = np.array([1,2,3,4])


In [3]:
A + B

array([4, 3, 7, 6])

In [4]:
A - B

array([ 2, -1,  1, -2])

In [5]:
A * B

array([ 3,  2, 12,  8])

In [7]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])

In [9]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [10]:
np.random.seed(0)

In [11]:
np.random.randn()

1.764052345967664

In [12]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [13]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [14]:
np.random.rand()

0.1965823616800535

In [15]:
np.random.randint(10)

0

In [16]:
np.random.choice([4, 2, 1, 3])

np.int64(3)

In [17]:
np.random.choice(['python', 'java', 'js'])

np.str_('java')

In [18]:
data = np.arange(10)

In [19]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.random.shuffle(data)

In [21]:
data

array([3, 6, 5, 8, 9, 7, 4, 2, 1, 0])

In [4]:
np.exp(1)

np.float64(2.718281828459045)

In [6]:
np.sqrt(4)

np.float64(2.0)

In [8]:
np.all([2, 3, 0])

np.False_

In [3]:
np.any([1, 2, 1])

np.True_

In [6]:
np.any([0, 0, 0])

np.False_

In [10]:
bool(1.3)

True

In [13]:
A = np.random.rand(5)
A

array([0.33047558, 0.79686565, 0.24605495, 0.97483184, 0.46901228])

In [14]:
np.argmax(A)

np.int64(3)

In [15]:
A[np.argmax(A)]

np.float64(0.974831841825775)

In [16]:
np.argmin(A)

np.int64(2)

In [17]:
A[np.argmin(A)]

np.float64(0.24605494885797352)

In [18]:
np.argsort(A)

array([2, 0, 4, 1, 3])

In [19]:
np.max(A)

np.float64(0.974831841825775)

In [20]:
np.min(A)

np.float64(0.24605494885797352)

In [21]:
np.mean(A)

np.float64(0.5634480607317303)

In [23]:
np.median(A)

np.float64(0.4690122790013922)

In [24]:
np.std(A)

np.float64(0.2784431962721708)

In [25]:
A = np.arange(20)

In [26]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
A = A.reshape(4,5)

In [31]:
A[:,-1]

array([ 4,  9, 14, 19])

In [35]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [36]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [38]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [39]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [40]:
A.shape

(4, 5)

In [42]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [45]:
A = np.arange(start=-10, stop=10, step=0.5)

In [46]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [47]:
A = A.reshape(10, -1)

In [48]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [49]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [52]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [53]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [54]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])