<a href="https://colab.research.google.com/github/fox2056/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np

In [59]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [60]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

In [61]:
v2 = np.array([-10, 10, 13])
v2

array([-10,  10,  13])

In [62]:
np.linalg.norm(v2)

np.float64(19.209372712298546)

In [63]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

np.float64(5.0)

In [64]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

np.float64(5.0990195135927845)

Mnożenie macierzy

In [66]:
A = np.array([[5, 3], [3, 9]])
A

array([[5, 3],
       [3, 9]])

In [68]:
B = np.array([[1], [-1]])
B

array([[ 1],
       [-1]])

In [70]:
Z = A@B
Z

array([[ 2],
       [-6]])

In [72]:
np.dot(A, B)

array([[ 2],
       [-6]])

In [73]:
X = np.array([[2, -1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [76]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [78]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

In [79]:
round(np.linalg.trace(A))

5

In [85]:
np.eye(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [86]:
A

array([[ 2,  4],
       [-1,  3]])

In [87]:
B = np.linalg.inv(A)

In [88]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [90]:
np.set_printoptions(precision=4, suppress=True)

A@B

array([[1., 0.],
       [0., 1.]])

In [92]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [93]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [95]:
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])

In [96]:
A

array([[ 2,  4],
       [ 1, -1]])

In [97]:
B

array([[10],
       [-1]])

In [98]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])