<a href="https://colab.research.google.com/github/fox2056/data-science-bootcamp/blob/main/getting_started_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch

torch.__version__

'2.8.0+cu126'

In [12]:
t1 = torch.tensor([1,2,3])
print(t1)
t2 = torch.tensor([[1,2], [3,4]])
print(t2)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


In [13]:
import numpy as np

np_array = np.array([5,6,7])
t3 = torch.tensor(np_array)
print(t3)

tensor([5, 6, 7])


In [14]:
t4 = torch.zeros((3,3))
print(t4)
t5 = torch.ones((3,3))
print(t5)
t6 = torch.eye(3)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [15]:
result = t1 + t3
print(result)
result = t3 - t1
print(result)
result = t1 * t3
print(result)
result = t3 / t1
print(result)

tensor([ 6,  8, 10])
tensor([4, 4, 4])
tensor([ 5, 12, 21])
tensor([5.0000, 3.0000, 2.3333])


In [17]:
t7 = torch.arange(9)
t8 = t7.reshape((3,3))
print(t8)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [18]:
dot_product = torch.dot(t1, t3)
print(dot_product)

tensor(38)


In [21]:
X = torch.randn(100, 10)
Y = torch.randn(100, 1)

In [22]:
input_size = 10
hidden_size = 5
output_size = 1

W1 = torch.randn(hidden_size, input_size).requires_grad_()
b1 = torch.zeros(hidden_size, requires_grad=True)
W2 = torch.randn(output_size, hidden_size).requires_grad_()
b2 = torch.zeros(output_size, requires_grad=True)

def simple_neural_net(x, W1, b1, W2, b2):
  z1 = torch.mm(x, W1.t()) + b1
  a1 = torch.sigmoid(z1)
  z2 = torch.mm(a1, W2.t()) + b2
  return z2

In [23]:
lr = 0.01
epochs = 100
loss_fn = torch.nn.MSELoss()

for epoch in range(epochs):
  y_pred = simple_neural_net(X, W1, b1, W2, b2)
  loss = loss_fn(y_pred.squeeze(), Y)
  loss.backward()

  with torch.no_grad():
    W1 -= lr * W1.grad
    b1 -= lr * b1.grad
    W2 -= lr * W2.grad
    b2 -= lr * b2.grad

  W1.grad.zero_()
  b1.grad.zero_()
  W2.grad.zero_()
  b2.grad.zero_()

  if epoch % 10 == 0:
    print(f"Epoch: {epoch} \t Loss: {loss.item()}")


Epoch: 0 	 Loss: 1.8787028789520264
Epoch: 10 	 Loss: 1.5800961256027222
Epoch: 20 	 Loss: 1.4522567987442017
Epoch: 30 	 Loss: 1.3879915475845337
Epoch: 40 	 Loss: 1.3482685089111328
Epoch: 50 	 Loss: 1.318770170211792
Epoch: 60 	 Loss: 1.2941666841506958
Epoch: 70 	 Loss: 1.2724082469940186
Epoch: 80 	 Loss: 1.2526501417160034
Epoch: 90 	 Loss: 1.2344971895217896


/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([100, 1])) that is different to the input size (torch.Size([100])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


### Training a feedforward neural network

In [24]:
import torch.nn as nn

In [25]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(10, 5)
    self.fc2 = nn.Linear(5, 1)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = self.fc2(x)
    return x

net = Net()
print(net)

Net(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)


In [26]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

In [27]:
for epoch in range(100):
  output = net(X)
  loss = loss_fn(output, Y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 1.3465931415557861
Epoch 2, Loss: 1.3169891834259033
Epoch 3, Loss: 1.2897229194641113
Epoch 4, Loss: 1.2645152807235718
Epoch 5, Loss: 1.241209864616394
Epoch 6, Loss: 1.2196192741394043
Epoch 7, Loss: 1.1996023654937744
Epoch 8, Loss: 1.1809840202331543
Epoch 9, Loss: 1.1636667251586914
Epoch 10, Loss: 1.1475356817245483
Epoch 11, Loss: 1.1325218677520752
Epoch 12, Loss: 1.1185805797576904
Epoch 13, Loss: 1.1055517196655273
Epoch 14, Loss: 1.0933644771575928
Epoch 15, Loss: 1.081954836845398
Epoch 16, Loss: 1.0712640285491943
Epoch 17, Loss: 1.0612385272979736
Epoch 18, Loss: 1.0518288612365723
Epoch 19, Loss: 1.0429900884628296
Epoch 20, Loss: 1.0346808433532715
Epoch 21, Loss: 1.0268627405166626
Epoch 22, Loss: 1.0195012092590332
Epoch 23, Loss: 1.0125638246536255
Epoch 24, Loss: 1.0060209035873413
Epoch 25, Loss: 0.9998457431793213
Epoch 26, Loss: 0.9940021634101868
Epoch 27, Loss: 0.9885163307189941
Epoch 28, Loss: 0.9836269617080688
Epoch 29, Loss: 0.9789995551109

### Training a recurrent neural network

In [30]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)
    def forward(self, x):
        h0 = torch.zeros(1, x.size(0), self.hidden_size).to(x.device)
        out, _ = self.rnn(x, h0) # get RNN output
        out = self.fc(out[:, -1, :]) # get last output
        return out

rnn = RNN(10, 20, 1)
print(rnn)

RNN(
  (rnn): RNN(10, 20, batch_first=True)
  (fc): Linear(in_features=20, out_features=1, bias=True)
)


In [31]:
X = torch.randn(100, 5, 10)
Y = torch.randn(100, 1)

In [32]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(rnn.parameters(), lr=0.01)

for epoch in range(100):
    output = rnn(X)
    loss = loss_fn(output, Y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

Epoch 1, Loss: 1.2307977676391602
Epoch 2, Loss: 1.2183032035827637
Epoch 3, Loss: 1.2067809104919434
Epoch 4, Loss: 1.196129322052002
Epoch 5, Loss: 1.1862598657608032
Epoch 6, Loss: 1.1770938634872437
Epoch 7, Loss: 1.1685622930526733
Epoch 8, Loss: 1.1606037616729736
Epoch 9, Loss: 1.1531637907028198
Epoch 10, Loss: 1.1461939811706543
Epoch 11, Loss: 1.139650821685791
Epoch 12, Loss: 1.1334956884384155
Epoch 13, Loss: 1.1276938915252686
Epoch 14, Loss: 1.122214436531067
Epoch 15, Loss: 1.1170291900634766
Epoch 16, Loss: 1.1121132373809814
Epoch 17, Loss: 1.1074436902999878
Epoch 18, Loss: 1.103000283241272
Epoch 19, Loss: 1.0987643003463745
Epoch 20, Loss: 1.0947190523147583
Epoch 21, Loss: 1.090849757194519
Epoch 22, Loss: 1.0871423482894897
Epoch 23, Loss: 1.0835844278335571
Epoch 24, Loss: 1.0801647901535034
Epoch 25, Loss: 1.0768733024597168
Epoch 26, Loss: 1.0737003087997437
Epoch 27, Loss: 1.0706374645233154
Epoch 28, Loss: 1.0676769018173218
Epoch 29, Loss: 1.0648115873336792

### Training an LSTM neural network

In [33]:
class LSTM(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(LSTM, self).__init__()
    self.hidden_size = hidden_size
    self.lstm = nn.LSTM(input_size, hidden_size, batch_first=True)
    self.fc = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    h0 = torch.zeros(1, x.size(0), self.hidden_size).to(x.device)
    c0 = torch.zeros(1, x.size(0), self.hidden_size).to(x.device)
    out, _ = self.lstm(x, (h0, c0)) # get LSTM output
    out = self.fc(out[:, -1, :])

    return out

lstm = LSTM(10, 20, 1) # 10 features, 20 hidden units, 1 output
print(lstm)

LSTM(
  (lstm): LSTM(10, 20, batch_first=True)
  (fc): Linear(in_features=20, out_features=1, bias=True)
)


In [34]:
X = torch.randn(100, 5, 10)
Y = torch.randn(100, 1)
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(lstm.parameters(), lr=0.01)

In [35]:
for epoch in range(100):
    output = lstm(X)
    loss = loss_fn(output, Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.9905087947845459
Epoch 2, Loss: 0.9894904494285583
Epoch 3, Loss: 0.9885101318359375
Epoch 4, Loss: 0.9875661730766296
Epoch 5, Loss: 0.9866567850112915
Epoch 6, Loss: 0.9857807159423828
Epoch 7, Loss: 0.9849362969398499
Epoch 8, Loss: 0.984122097492218
Epoch 9, Loss: 0.9833366870880127
Epoch 10, Loss: 0.9825788736343384
Epoch 11, Loss: 0.9818474054336548
Epoch 12, Loss: 0.9811410307884216
Epoch 13, Loss: 0.980458676815033
Epoch 14, Loss: 0.979799211025238
Epoch 15, Loss: 0.9791616201400757
Epoch 16, Loss: 0.978545069694519
Epoch 17, Loss: 0.9779481291770935
Epoch 18, Loss: 0.9773706197738647
Epoch 19, Loss: 0.9768112301826477
Epoch 20, Loss: 0.9762691259384155
Epoch 21, Loss: 0.9757438898086548
Epoch 22, Loss: 0.9752342700958252
Epoch 23, Loss: 0.9747399091720581
Epoch 24, Loss: 0.9742599725723267
Epoch 25, Loss: 0.9737939238548279
Epoch 26, Loss: 0.973341166973114
Epoch 27, Loss: 0.9729009866714478
Epoch 28, Loss: 0.9724728465080261
Epoch 29, Loss: 0.9720562696456909

### Training a convolutional neural network

In [36]:
class ConvNet(nn.Module):
    def __init__(self,
      input_size,
      hidden_size,
      output_size,
      kernel_size,
      seq_length):
      super(ConvNet, self).__init__()
      self.conv1 = nn.Conv1d(input_size, hidden_size, kernel_size)
      self.fc = nn.Linear(hidden_size*(seq_length-kernel_size+1), output_size)

    def forward(self, x):
      x = x.transpose(1, 2)
      out = torch.relu(self.conv1(x))
      out = out.view(out.size(0), -1) # flatten the tensor
      out = self.fc(out)

      return out

convnet = ConvNet(5, 20, 1, 3, 10)
print(convnet)

ConvNet(
  (conv1): Conv1d(5, 20, kernel_size=(3,), stride=(1,))
  (fc): Linear(in_features=160, out_features=1, bias=True)
)


In [37]:
X = torch.randn(100, 10, 5)
Y = torch.randn(100, 1)

In [38]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(convnet.parameters(), lr=0.01)

for epoch in range(100):
    output = convnet(X)
    loss = loss_fn(output, Y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 1.1577041149139404
Epoch 2, Loss: 1.1472264528274536
Epoch 3, Loss: 1.1370139122009277
Epoch 4, Loss: 1.127050518989563
Epoch 5, Loss: 1.117323637008667
Epoch 6, Loss: 1.1078319549560547
Epoch 7, Loss: 1.0985636711120605
Epoch 8, Loss: 1.0895147323608398
Epoch 9, Loss: 1.0806804895401
Epoch 10, Loss: 1.072043776512146
Epoch 11, Loss: 1.0635981559753418
Epoch 12, Loss: 1.0553371906280518
Epoch 13, Loss: 1.0472521781921387
Epoch 14, Loss: 1.0393387079238892
Epoch 15, Loss: 1.0315912961959839
Epoch 16, Loss: 1.024001955986023
Epoch 17, Loss: 1.016566514968872
Epoch 18, Loss: 1.0092804431915283
Epoch 19, Loss: 1.0021404027938843
Epoch 20, Loss: 0.9951435923576355
Epoch 21, Loss: 0.9882773756980896
Epoch 22, Loss: 0.9815418720245361
Epoch 23, Loss: 0.9749428033828735
Epoch 24, Loss: 0.9684750437736511
Epoch 25, Loss: 0.9621230363845825
Epoch 26, Loss: 0.9558832049369812
Epoch 27, Loss: 0.9497590661048889
Epoch 28, Loss: 0.943746030330658
Epoch 29, Loss: 0.9378422498703003
Epo